In [7]:
import pandas as pd
df = pd.read_csv('IPL.csv')
#display first five rows
df.head()

/tmp/ipykernel_4229/3939086764.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('IPL.csv')

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [8]:
#Explore the dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(35)
memory usage: 135.0+ MB

In [9]:
#Check missing values for every column
df.isnull().sum()

Unnamed: 0               0
match_id                 0
date                     0
match_type               0
event_name               0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
next_batter         270085
striker_out              0
Length: 65, dtype: int64

In [11]:
# Check missing values
print(df.isnull().sum())

# Fill numerical missing values with the median
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill text (object) columns with "Unknown"
object_cols = df.select_dtypes(include=['object']).columns

for col in object_cols:
    df[col] = df[col].fillna("Unknown")

# Fill Boolean columns with False
bool_cols = df.select_dtypes(include=['bool']).columns

for col in bool_cols:
    df[col] = df[col].fillna(False)

# Verify that missing values have been handled
print(df.isnull().sum())

Unnamed: 0               0
match_id                 0
date                     0
match_type               0
event_name               0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
next_batter         270085
striker_out              0
Length: 65, dtype: int64
Unnamed: 0          0
match_id            0
date                0
match_type          0
event_name          0
                   ..
batter_balls        0
bowler_wicket       0
batting_partners    0
next_batter         0
striker_out         0
Length: 65, dtype: int64

In [12]:
# Check duplicate records
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicate records
df.drop_duplicates(inplace=True)

# Verify duplicates are removed
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows: 0
Duplicate rows after cleaning: 0

In [13]:
# Remove extra spaces and convert text to title case
text_cols = df.select_dtypes(include=['object']).columns

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

print("Text columns cleaned successfully.")

Text columns cleaned successfully.

In [14]:
# Convert date column to datetime format
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Ensure ball number is float
df["ball_no"] = df["ball_no"].astype(float)

print(df.dtypes)

Unnamed: 0                   int64
match_id                     int64
date                datetime64[ns]
match_type                  object
event_name                  object
                         ...
batter_balls                 int64
bowler_wicket                int64
batting_partners            object
next_batter                 object
striker_out                   bool
Length: 65, dtype: object

In [15]:
# Rename columns for consistency
df.rename(columns={
    "ball_no": "ball_number",
    "bat_pos": "batting_position",
    "runs_extras": "extra_runs",
    "runs_total": "total_runs",
    "runs_bowler": "bowler_runs",
    "team_wicket": "team_wickets",
    "event_match_no": "event_match_number",
    "match_number": "match_no"
}, inplace=True)

In [16]:
 # Remove unnecessary column
df.drop(columns=["Unnamed: 0"], inplace=True)
 # Create Strike Rate
df["strike_rate"] = (df["batter_runs"] / df["batter_balls"]) * 100

In [18]:
# Display updated dataset information
print(df.info())

# Display first five rows
print(df.head())

# Check remaining missing values
print(df.isnull().sum())

# Check duplicates
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   match_id            283678 non-null  int64
 1   date                283678 non-null  datetime64[ns]
 2   match_type          283678 non-null  object
 3   event_name          283678 non-null  object
 4   innings             283678 non-null  int64
 5   batting_team        283678 non-null  object
 6   bowling_team        283678 non-null  object
 7   over                283678 non-null  int64
 8   ball                283678 non-null  int64
 9   ball_number         283678 non-null  float64
 10  batter              283678 non-null  object
 11  batting_position    283678 non-null  int64
 12  runs_batter         283678 non-null  int64
 13  balls_faced         283678 non-null  int64
 14  bowler              283678 non-null  object
 15  valid_ball          283678 non-null  int64
 16  extra_runs          283678 non-null  int64
 17  total_runs          283678 non-null  int64
 18  bowler_runs         283678 non-null  int64
 19  runs_not_boundary   283678 non-null  bool
 20  extra_type          283678 non-null  object
 21  non_striker         283678 non-null  object
 22  non_striker_pos     283678 non-null  int64
 23  wicket_kind         283678 non-null  object
 24  player_out          283678 non-null  object
 25  fielders            283678 non-null  object
 26  runs_target         283678 non-null  float64
 27  review_batter       283678 non-null  object
 28  team_reviewed       283678 non-null  object
 29  review_decision     283678 non-null  object
 30  umpire              283678 non-null  object
 31  umpires_call        283678 non-null  bool
 32  player_of_match     283678 non-null  object
 33  match_won_by        283678 non-null  object
 34  win_outcome         283678 non-null  object
 35  toss_winner         283678 non-null  object
 36  toss_decision       283678 non-null  object
 37  venue               283678 non-null  object
 38  city                283678 non-null  object
 39  day                 283678 non-null  int64
 40  month               283678 non-null  int64
 41  year                283678 non-null  int64
 42  season              65536 non-null   object
 43  gender              283678 non-null  object
 44  team_type           283678 non-null  object
 45  superover_winner    283678 non-null  object
 46  result_type         283678 non-null  object
 47  method              283678 non-null  object
 48  balls_per_over      283678 non-null  int64
 49  overs               283678 non-null  int64
 50  event_match_number  163840 non-null  object
 51  stage               283678 non-null  object
 52  match_no            283678 non-null  object
 53  team_runs           283678 non-null  int64
 54  team_balls          283678 non-null  int64
 55  team_wickets        283678 non-null  int64
 56  new_batter          283678 non-null  object
 57  power_surge_start   0 non-null       float64
 58  batter_runs         283678 non-null  int64
 59  batter_balls        283678 non-null  int64
 60  bowler_wicket       283678 non-null  int64
 61  batting_partners    283678 non-null  object
 62  next_batter         283678 non-null  object
 63  striker_out         283678 non-null  bool
 64  strike_rate         282917 non-null  float64
dtypes: bool(3), datetime64[ns](1), float64(4), int64(23), object(34)
memory usage: 135.0+ MB
None
   match_id       date match_type             event_name  innings  \
0    335982 2008-04-18        T20  Indian Premier League        1
1    335982 2008-04-18        T20  Indian Premier League        1
2    335982 2008-04-18        T20  Indian Premier League        1
3    335982 2008-04-18        T20  Indian Premier League        1
4    335982 2008-04-18        T20  Indian Premier League        1

            batting_team                 bowling_team  over  ball  \
0  Kolkata Knight Riders  Royal Challengers Bangalore     0     1
1  Kolkata Knight Riders  Royal Challengers Bangalore     0     2
2  Kolkata Knight Riders  Royal Challengers Bangalore     0     3
3  Kolkata Knight Riders  Royal Challengers Bangalore     0     3
4  Kolkata Knight Riders  Royal Challengers Bangalore     0     4

   ball_number  ... team_wickets  new_batter  power_surge_start  batter_runs  \
0          0.1  ...            0     Unknown                NaN            0
1          0.2  ...            0     Unknown                NaN            0
2          0.3  ...            0     Unknown                NaN            0
3          0.3  ...            0     Unknown                NaN            0
4          0.4  ...            0     Unknown                NaN            0

  batter_balls  bowler_wicket               batting_partners  next_batter  \
0            1              0  ('Bb Mccullum', 'Sc Ganguly')      Unknown
1            1              0  ('Bb Mccullum', 'Sc Ganguly')      Unknown
2            1              0  ('Bb Mccullum', 'Sc Ganguly')      Unknown
3            2              0  ('Bb Mccullum', 'Sc Ganguly')      Unknown
4            3              0  ('Bb Mccullum', 'Sc Ganguly')      Unknown

   striker_out  strike_rate
0        False          0.0
1        False          0.0
2        False          0.0
3        False          0.0
4        False          0.0

[5 rows x 65 columns]
match_id              0
date                  0
match_type            0
event_name            0
innings               0
                   ...
bowler_wicket         0
batting_partners      0
next_batter           0
striker_out           0
strike_rate         761
Length: 65, dtype: int64
0

In [19]:
# Save the cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

print("Dataset cleaned successfully!")

Dataset cleaned successfully!